# ES2021

- Promise.any

여러 개의 프로미스 중에 하나라도 성공하면 바로 resolve되고, 모든 프로미스가 다 실패하면 reject됩니다. reject 시에는 AggregationError가 발생합니다.

```javascript
Promise.any([
  Promise.reject(1),
  Promise.reject(3),
  Promise.resolve(5), // 이게 가장 먼저 성공
]).then((result) => console.log(result === 5));
Promise.any([
  Promise.reject(1),
  Promise.reject(3),
  Promise.reject(5),
]).catch((result) => console.log(result)); // AggregationError 
```

Promise.race와 헷갈려하시는 분이 많을 것 같은데, Promise.race는 성공하든 실패하든, 가장 먼저 끝나는 것이 resolve되고, Promise.any는 먼저 성공(반드시 성공해야 함)하는 것이 resolve됩니다.

```javascript
Promise.race([
  Promise.reject(1), // 이게 가장 먼저 끝남
  Promise.reject(3),
  Promise.resolve(5),
]).catch((result) => console.log(result === 1));
```

# ES2022

- Error Cause
에러 객체에 좀 더 구체적인 원인을 적는 cause 속성이 추가되었습니다.

```javascript
const e = new Error('에러', { cause: '원인' });
e.cause; // 원인
```

[출처](https://www.zerocho.com/category/ECMAScript)